from django.urls import path

from src.store.views import (
    AuctionEndView,
    BuyRejectView,
    BuyTokenView,
    CreateCollectionView,
    CreateView,
    FastSearchTokenView,
    GetCollectionChartView,
    GetCollectionTradeDataView,
    GetCollectionView,
    GetMostBiddedView,
    GetRelatedView,
    GetView,
    MakeBid,
    MintRejectView,
    ReportView,
    SearchView,
    SetCoverView,
    SupportView,
    TokenBurnView,
    TokenRemoveFromSaleView,
    TokenSetOnAucSaleView,
    TokenSetOnSaleView,
    TransactionTrackerView,
    TransferOwned,
    VerificateBetView,
    get_bids,
    get_categories,
    get_favorites,
    get_hot_bids,
    get_max_price,
    trending_collections,
    trending_tokens,
)

urlpatterns = [
    path("create_token/", CreateView.as_view()),
    path("create_collection/", CreateCollectionView.as_view()),
    path("most_bidded/", GetMostBiddedView.as_view()),
    path("track_transaction/", TransactionTrackerView.as_view()),
    path("search/", SearchView.as_view()),
    path("presearch/", FastSearchTokenView.as_view()),
    path("collection/<str:param>/", GetCollectionView.as_view()),
    path("collection/<str:param>/chart/", GetCollectionChartView.as_view()),
    path("collection/<str:param>/trade_data/", GetCollectionTradeDataView.as_view()),
    path("buy/", BuyTokenView.as_view()),
    path("categories/", get_categories),
    path("max_price/", get_max_price),
    path("bids/make_bid/", MakeBid.as_view()),
    path("hot_bids/", get_hot_bids),
    path("report/", ReportView.as_view()),
    path("set_cover/", SetCoverView.as_view()),
    path("favorites/", get_favorites),
    path("support/", SupportView.as_view()),
    path("mint-reject/", MintRejectView.as_view()),
    path("buy-reject/", BuyRejectView.as_view()),
    path("trending_tokens/", trending_tokens),
    path("trending_collections/", trending_collections),
    path("token/<int:token_id>/", GetView.as_view()),
    path("token/<int:token_id>/set_on_sale/", TokenSetOnSaleView.as_view()),
    path("token/<int:token_id>/set_on_auction/", TokenSetOnAucSaleView.as_view()),
    path("token/<int:token_id>/remove_from_sale/", TokenRemoveFromSaleView.as_view()),
    path("token/<int:token_id>/burn/", TokenBurnView.as_view()),
    path("token/<int:token_id>/transfer/", TransferOwned.as_view()),
    path("token/<int:token_id>/get_bids/", get_bids),
    path("token/<int:token_id>/related/", GetRelatedView.as_view()),
    path("token/<int:token_id>/verificate_bet/", VerificateBetView.as_view()),
    path("token/<int:token_id>/end_auction/", AuctionEndView.as_view()),
]
